### ISSUE TITLE
newly added helm istioctl failing on master

### ISSUE THREAD

**Issue by cmluciano** [istio-releases/daily-release#1114]
The new [helm istioctl script](https://github.com/istio-releases/daily-release/blob/master/prow/istioctl-tests.sh) is failing on master.This might indicate an actual istioctl test failure but the logs are not very verbose and they doesn't point to a precise failure point.

Example failure https://storage.googleapis.com/istio-prow/pull/istio-releases_daily-release/1113/istioctl-tests/29/build-log.txt

**Comment by cmluciano** [comment]
cc @hklai

**Comment by hklai** [comment]
Thanks

The test caught a change in release automation. I have just fixed the test and qualification have just passed on both master and release-1.0.
